/**
 * Content-hashes the image folders we actively edit, so their URLs can honestly
 * be served `immutable`.
 *
 *   node scripts/hash-assets.mjs
 *
 * Renames public/sectors/media.webp -> public/sectors/media.<hash>.webp and
 * writes src/lib/asset-manifest.ts mapping the stable logical key to it.
 *
 * Why: without this, replacing an image reuses its URL. Anything already
 * holding that URL — a CDN edge, a browser, an open tab — keeps serving the
 * previous bytes, and a year-long immutable header makes that permanent. With
 * the hash in the name, new content means a new URL and the old one is simply
 * no longer referenced.
 *
 * Re-runnable: an existing hash is stripped before the new one is computed, so
 * running it twice on unchanged files is a no-op.
 */
import { createHash } from "node:crypto";
import { readdir, readFile, rename, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";

const FOLDERS = ["public/sectors", "public/why", "public/services", "public/partners", "public/flags", "public/team", "public/branding", "public/clients"];
const IMAGE = /\.(webp|png|jpe?g|avif|svg)$/i;
const HASHED = /\.[0-9a-f]{8}(\.[a-z0-9]+)$/i;

/** "media.a1b2c3d4.webp" -> "media.webp" */
const logicalName = (file) => file.replace(HASHED, "$1");

const manifest = {};
let renamed = 0;

for (const folder of FOLDERS) {
  if (!existsSync(folder)) continue;
  for (const file of (await readdir(folder)).filter((f) => IMAGE.test(f))) {
    const full = path.join(folder, file);
    const buf = await readFile(full);
    const hash = createHash("sha256").update(buf).digest("hex").slice(0, 8);

    const logical = logicalName(file);
    const ext = path.extname(logical);
    const base = logical.slice(0, -ext.length);
    const hashed = `${base}.${hash}${ext}`;

    if (file !== hashed) {
      await rename(full, path.join(folder, hashed));
      console.log(`${file}  ->  ${hashed}`);
      renamed++;
    }
    const key = `${path.basename(folder)}/${logical}`;
    manifest[key] = `/${path.basename(folder)}/${hashed}`;
  }
}

const entries = Object.keys(manifest)
  .sort()
  .map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(manifest[k])},`)
  .join("\n");

await writeFile(
  "src/lib/asset-manifest.ts",
  `// GENERATED by scripts/hash-assets.mjs — do not edit by hand.
// Run \`node scripts/hash-assets.mjs\` after adding or replacing an image.

const manifest: Record<string, string> = {
${entries}
};

/** Resolve a stable key like "sectors/media.webp" to its hashed public URL. */
export function asset(key: string): string {
  const hit = manifest[key];
  if (!hit) throw new Error(\`Unknown asset "\${key}" — run: node scripts/hash-assets.mjs\`);
  return hit;
}
`,
  "utf8"
);

console.log(`\n${Object.keys(manifest).length} assets in manifest, ${renamed} renamed.`);
